### ISSUE TITLE
Error when converting the file

### ISSUE THREAD

**Issue by baditaflorin** [mvexel/geojson2maproulette#3]
python geojson2maproulette.py sidewalk_romania.yaml 
Traceback (most recent call last):
  File "geojson2maproulette.py", line 37, in <module>
    config = yaml.load(config_file)
  File "/usr/local/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "sidewalk_romania.yaml", line 2, column 1
expected <block end>, but found '<block mapping start>'
  in "sidewalk_romania.yaml", line 11, column 2
florinb@florinb-VirtualBox:~/geojson2maproulette$ ^C
florinb@florinb-VirtualBox:~/geojson2maproulette$

**Comment by baditaflorin** [comment]
With this is working https://gist.githubusercontent.com/anonymous/310005dc1dcf08f5c4a7/raw/74aa0d6a845a20511d0c450d715dab23d2a6c0d6/overpass.geojson

With this i get the error 

https://gist.githubusercontent.com/anonymous/7f18bf7bd5da6bd5c73ba593272a309e/raw/1b94749830dfe6fe55464b4dc1b282366218bcc0/overpass.geojson
